### ISSUE TITLE
Client Beta 7.4 Throws Exception on Save when using DataServiceCollection to track entity change

### ISSUE THREAD

**Issue by mtroth-microsoft** [OData/odata.net#997] opened 2017-11-16 22:03 UTC
*Short summary (3-5 sentences) describing the issue.*

### Assemblies affected

Microsoft.OData.Client

### Reproduce steps

I have a repro that uses northwnd.

In pseudo code:
DataServiceCollection dsc = new DataServiceCollection(context.Products)
dsc[0].SupplierID = NULL
var result = context.SaveChangesAsync(
    SaveChangesOptions.BatchWithSingleChangeset | 
    SaveChangesOptions.PostOnlySetProperties)

### Expected result

specified product is updated with a null supplier id or we get a store error because the FK can't be null. point is that the request goes to the server and the server logic gets to execute.

### Actual result

ArgumentException before the request is even sent to the server.

### Additional detail

N/A

**Comment by biaol-odata** [comment] 2017-11-19 18:42
@mtroth-microsoft Do you have any information about whether it is a regression? Also not sure whether such ArgumentException Is due to caller using invalid argument or is a bug for the client library?

**Comment by mtroth-microsoft** [comment] 2017-11-20 22:52
The argument is not invalid as it does work in the previous version of the client library. So it does appear to be a regression.

**Comment by habbes** [comment] 2020-08-03 14:27
@mtroth-microsoft are you still experiencing this issue in newer versions of the library? I was not able to reproduce the issue. In my case, the client successfully sent the request to the server. However, for this to work you must enable entity tracking, i.e. your entity class must implement `INotifyPropertyChanged`, otherwise you'd get an `InvalidOperationException`.

**Comment by habbes** [comment] 2020-08-10 09:26
@mtroth-microsoft I'm closing this issue since we could not reproduce it and it's very likely that the issue was fixed in the versions that have been released since the time it was posted. However, please open an issue if you encounter this problem again.

**Closed by habbes** 2020-08-10 09:26 UTC
Labels: P2, client, regression
