### ISSUE TITLE
ODataReader doesn't populate InstanceAnnotations on Properties

### ISSUE THREAD

**Issue by JefWight** [OData/odata.net#547] opened 2016-04-27 02:24 UTC
When using the ODataReader to read a request body, core "odata." annotations are being read (and applied) but not added to the InstanceAnnotations collection.  Annotations with no prefix get skipped altogether.  Only annotations with a non-"odata." prefix appear in a properties InstanceAnnotations..
### Assemblies affected

Microsoft.OData.Core .Net lib 6.15
### Reproduce steps

Request Body

```
{
    "Start@odata.type": "#DateTimeOffset",
    "Start@foo": "bar",
    "Start@foo.bar": "bar",
    "Start":"2016-03-09T20:04:36Z",
}
```

Reader code:

```
ODataReader odataReader...;
oDataReader.Read();
var entry = (ODataEntry)oDataReader.Item
```
### Expected result

```
entry.Properties[0]
  .Value is DateTimeOffset
  .InstanceAnnotations.Length == 3
  .InstanceAnnotations contains "foo", "foo.bar", "odata.type"
```
### Actual result

```
entry.Properties[0]
  .Value is DateTimeOffset
  .InstanceAnnotations.Length == 1
  .InstanceAnnotations contains "foo.bar"
```
### Additional details

One of the reasons we are looking for this functionality is when using OpenTypes, where we can infer a property's type from the value specified, however we intend to do some additional work to index properties when the client explicitly specifies type information for a property.

**Comment by JefWight** [comment] 2016-04-27 17:24
It appears I'm slightly mistaken.  Using:
```
{
    "Start@odata.type": "#DateTimeOffset",
    "Start@foo": "bar",
    "Start":"2016-03-09T20:04:36Z",
}
```
Yields:
```
entry.Properties[0].Value is DateTimeOffset
entry.Properties[0].InstanceAnnotations.Length == 1
```

It appears that annotations with no "prefix." in them get "odata." prepended, any odata annotation we don't know about gets skipped altogether, and no odata annotations show up in the property annotations.

I would imagine that an annotation with no prefix, where its an unknown odata annotation should be treated as simply an unknown annotation and added to the list (with no prefix).  We still need to be able to see that an odata annotation was present though.  Updated the bug to reflect some things.

**Comment by LaylaLiu** [comment] 2016-04-29 08:15
@JefWight Thank you for reporting all of the issues (include #546). 

This is a known issue in ODataLib that all "odata." annotations do not show up in the property instance annotations. 

We would like to have it to be fixed in the ODataLib, but at this point we are spending all resources on an breaking changes release that have a hard deadline. So we want to know the priority of these issues on your side. We would happily accept your pull requests as well. So if you have time to implement the two features, we'd love to merge it into the library.

**Comment by JefWight** [comment] 2016-04-29 17:01
I will happily code it and submit a pull request (in fact, I already have a rough set of changes to fix it), but would like your input on the expected behavior.

For example, will clients break if we start adding all "odata." annotations to the "InstanceAnnotations" collection?

**Comment by LaylaLiu** [comment] 2016-05-19 09:40
@JefWight, Sorry to reply you so late, on client side, these instance annotations will be used to set some values on client side. like TotalCount in response or the editlink in descriper. we need to make sure all these properties are set correctly. besides, I think client should not be broken. We can use the test cases in full/Lith/E2E.sln to test it.

**Comment by object** [comment] 2016-07-25 20:16
And what about expand annotations, like "entity@odata.nextlink". Are they read or not? If I have payload like this:

{
  "@odata.context":"https://myfeed.dynamics.com/api/data/v8.1/$metadata#accounts(name,Account_Tasks)","value":[
    {
      "@odata.etag":"W/\"596351\"","name":"Account 1","accountid":"5f4c87e4-4952-e611-80dd-c4346bacfc18","Account_Tasks":[
        
      ],"Account_Tasks@odata.nextLink":"https://myfeed.dynamics.com/api/data/v8.1/accounts(5f4c87e4-4952-e611-80dd-c4346bacfc18)/Account_Tasks"
    }
  ]
}

Then should Account_Tasks@odata.nextLink appear as instance annotation or it's not currently supported?

**Comment by mikepizzo** [comment] 2017-04-20 23:06
See my comments in the related PR.

The fact that control information is returned as instance annotations is specific to the JSON format; the set of instance annotations returned through the API must not depend on the serialization format; regardless of the underlying format, the API should appear the same.

Can we address your scenario by differentiating between explicit and implicit type information, in a format-neutral way, rather than have the collection of instance annotations vary by format.

**Comment by madansr7** [comment] 2019-10-07 21:39
Cleaning up old issues, not exposing format specific control information as annotations is by design. If you still have a need to differentiate between implicit and explicit type, please open a separate issue.

**Closed by madansr7** 2019-10-07 21:39 UTC
Labels: OData.Client, P2
