### ISSUE TITLE
[7.0.0] An incompatible primitive type 'Edm.Int32[Nullable=False]' was found for an item that was expected to be of type 'Edm.String[Nullable=True]

### ISSUE THREAD

**Issue by xuzhg** [OData/odata.net#724] opened 2016-11-21 03:25 UTC
See detail at: https://github.com/OData/WebApi/issues/855

**Comment by AlanWong-MS** [comment] 2017-05-31 01:12
Per comment in #855 by "tyrius02": Issue OData/odata.net#724 is a duplicate of OData/odata.net#706. The latter contains a bit more detail.

**Comment by ElizabethOkerio** [comment] 2022-08-01 06:10
fixed by thos pr: https://github.com/OData/odata.net/pull/756

**Closed by ElizabethOkerio** 2022-08-01 06:10 UTC
Labels: P2
