### ISSUE TITLE
ExecuteAsync Does Not Timeout

### ISSUE THREAD

**Issue by tan00001** [OData/odata.net#2413] opened 2022-05-22 02:41 UTC
.NET Framework version of Microsoft.OData.Client,DataServiceQuery<TElement>.ExecuteAsync(CancellationToken cancellationToken) never times out

### Assemblies affected

Microsoft.OData.Client version 7.11.0.0

### Reproduce steps

1. Set DataServiceContext.TimeOut to something like 3 seconds
2. Make sure that the server action to be tested will take longer than the time specified in Step1. I added a Thread.Sleep(300000) on the server side for the action to be tested.
3. Call DataServiceQuery<TSource>.ExecuteAsync(CancellationToken cancellationToken) on the server action setup in Setp 2.
4. The call never times out.
 
### Expected result

The call should timeout in 3 seconds, or whatever time you chose in Step 1

### Actual result

The call never times out. In contrast, DataServiceQuery<TSource>.Execute() times out as expected.

**Comment by habbes** [comment] 2022-05-30 05:35
@tan00001 I was not able to reproduce issue. I tested `.Execute()`, `.ExecuteAsync()` and `.ExecuteAsync(CancellationToken)` and in all cases I was getting a timeout exception.

Could you share more information about how you're creating the `DataServiceQuery`?

**Comment by habbes** [comment] 2022-06-07 12:49
Closing this because I was not able to reproduce the issue.

**Closed by habbes** 2022-06-07 12:49 UTC
Labels: bug
