### ISSUE TITLE
OData v4 client code generator - Combined length of user strings used by the program exceeds allowed limit

### ISSUE THREAD

**Issue by javism1** [OData/odata.net#1220] opened 2018-07-31 10:36 UTC
OData v4 client code generator - Get error [Error code: CS8103] "Combined length of user strings used by the program exceeds allowed limit. Try to decrease use of string literals." when building project with oDataClient.cs file

### Assemblies affected

Using:
OData v4 client code generator version 7.5.0 
Microsoft.OData.Client 7.5.0
Microsoft.OData.Core 7.5.0
Microsoft.OData.Edm 7.5.0
Microsoft.Spatial 7.5.0

### Reproduce steps

1. Point the oDataClient.tt file to use the Dynamics 365 for Finance and Operations metadata file
2. Generate oDataClient.cs file by running custom tool on oDataClient.tt file
3. Build project

### Expected result

Successful build

### Actual result

Get the error message: "Combined length of user strings used by the program exceeds allowed limit"

### Additional detail

This is currently happening when using the MS Client code generator with the EDMX file from Dynamics 365 for Finance and Operations (App. version 8.0). It seems like the list of data entities returned on the EDMX file is too large to be handled by Visual Studio. 

Other users did some further investigation:
https://github.com/Microsoft/Dynamics-AX-Integration/issues/17

**Comment by biaol-odata** [comment] 2018-07-31 16:40
Looks like a string length limit issue imposed by Visual Studio. Can this issue be avoided by reducing the string length?

**Comment by fraga** [comment] 2018-08-01 00:55
+1 on this one. We're also having issues generating metadata. File is too big and looking for alternatives.

**Comment by fraga** [comment] 2018-08-02 13:07
@biaol-odata thanks for the attention. D365 provides us the metadata and currently, as far as I know, we have no means to select different entities to make the file smaller. So, as specified by @javism1 D365 v8.0 PU15 creates a huge edmx metadata (around 15mb) and it gives us trouble when generating the odata client failing with _"Combined length of user strings used by the program exceeds allowed limit. Try to decrease use of string literals."_. I do have a sample edmx file if you want and if you allow I can email it to you.

**Comment by KanishManuja-MS** [comment] 2018-08-06 17:48
@fraga can you email me the sample edmx file at kamanuja@microsoft.com?

**Comment by fraga** [comment] 2018-08-06 22:12
Hi @KanishManuja-MS, email sent. Thanks.

**Comment by anhhainguyen** [comment] 2018-08-07 14:39
i'm having the same issue for OData D365. Is there a workaround for this?

**Comment by fraga** [comment] 2018-08-07 15:10
Hi @anhhainguyen the only workaround for now for the string limitation that I know is by shrinking the file yourself, i.e. removing entities you don't use and also, as per @javism1, you can comment the edmx string line in the custom tool cs (check his comment on this thread). Hope it helps.

**Comment by fraga** [comment] 2018-08-08 20:17
Thanks for sharing @toryb

**Comment by grubby19870810** [comment] 2018-09-16 16:00
@toryb It is working now, thank your sharing

**Comment by xuzhg** [comment] 2018-09-17 18:05
Chang-set merged and released in 7.5.1.

**Closed by xuzhg** 2018-09-17 18:05 UTC
Labels: question

**Comment by Nilraj12** [comment] 2018-09-26 09:41
@xuzhg 
You have mentioned it is merged in 7.5.1 version. Are you referring OData client code generator extension or OData.Client references? Because I've updated references in project but this issue is still there.

**Comment by KanishManuja-MS** [comment] 2018-09-26 17:27
@Nilraj12 It looks like the extension version 7.5.1 never got released. I will try and update that. The issue is fixed in the repo but the extension is still not updated.

**Comment by MamathaKona** [comment] 2019-01-07 19:46
@KanishManuja-MS  I have installed version 7.5.3.I am still getting this error! am I missing something?

**Comment by KanishManuja-MS** [comment] 2019-01-07 20:10
@MamathaKona Are you using OData client code generator or the connected services extension?

**Comment by MamathaKona** [comment] 2019-01-07 20:11
@KanishManuja-MS I am using OData Client code generator!

**Comment by RameshwariSah** [comment] 2019-04-11 11:39
Hi all,

I am also getting the same issue. Current version of Microsoft.Odata.Client is 7.5.4 and the class library is in net framework 4.6.1. The ttinclude file uses csdl reader. However, I still get the same issue. Appreciate any help !

Regards,
Rameshwari

**Comment by prezasoftwares** [comment] 2019-04-25 13:31
Hi @RameshwariSah,

I was getting that issue. Now it is working fine. The class libary version I am using is 4.5.2. I have updated the Odata libraries to 7.5.4 using Nuget.
I have set the TempFilePath variable to a local folder + file name.xml, by doing this, the xml definition file was saved locally, avoiding this "combined string" error.
After this, you have to replace the "" to " in generated xml file.

**Comment by KasthuriNallathambi** [comment] 2019-05-22 05:04
Hi @prezasoftwares ,

As you said  i have set value for TempFilePath to localFoder+Test.xml
it generated the file with name test

What i need to replace in the generated file .. you have mentioned replace the "to" .. what it means can you explain in deep..

**Comment by Neetha-Ravva** [comment] 2019-06-15 14:44
hi toryb i am not clear with your 4B and 4C points could you clearly explain them.

**Comment by RameshwariSah** [comment] 2019-06-23 19:50
> Hi @RameshwariSah,
> 
> I was getting that issue. Now it is working fine. The class libary version I am using is 4.5.2. I have updated the Odata libraries to 7.5.4 using Nuget.
> I have set the TempFilePath variable to a local folder + file name.xml, by doing this, the xml definition file was saved locally, avoiding this "combined string" error.
> After this, you have to replace the "" to " in generated xml file.

Thank you @prezasoftwares . The solution worked. However, It takes long to modify & save the generated xml file.

**Comment by swidz** [comment] 2019-07-22 09:16
Hi, I was able to generate the temp xml file avoiding the "combined string" error.  I have noticed that each time I update the .tt file the temp.xml file grows, the EDMX definition inside is appended. Is this a bug and the file should be overwritten instead or it happens for a reason an the file should be deleted each time we regenerate?

**Comment by kennysaelen** [comment] 2020-02-07 13:10
You can indeed just use the following line in the .tt file:
public const string TempFilePath = "<put an xml file path here>";

This wil generate the edmx in a file on disk and work with that also avoiding the whole issue.

**Comment by hiteshgoldeneye** [comment] 2020-04-05 13:54
> You can indeed just use the following line in the .tt file:
> public const string TempFilePath = "";
> 
> This wil generate the edmx in a file on disk and work with that also avoiding the whole issue.

This is the apt solution to this issue, Thanks a lot kennysaelen!
