### ISSUE TITLE
Support for Function Parameter Collection Complex Type

### ISSUE THREAD

**Issue by premiaware** [OData/odata.net#636] opened 2016-07-14 16:24 UTC
My question is simple, OData Client support OData Function with Collection Complex Parameter type?
I have try to use 
```c#
    public class AnagraficaQueryFieldsMap1  // my complex type
    {
        public int ID { get; set; }
    }
```
In the register :
```c#
builder.ComplexType<<AnagraficaQueryFieldsMap1>>();
var func1 = builder.Function("ListaAnagrafiche").Returns<string>();
func1.CollectionParameter<AnagraficaQueryFieldsMap1>("param") 

// my controller 

[HttpGet]
[ODataRoute("ListaAnagrafiche(param={param})")]
public IHttpActionResult ListaAnagrafiche([FromODataUri] IEnumerable<AnagraficaQueryFieldsMap1> param)
{
....
}
```
Using OData Function I receive IIS 500 internal error, if i use OData Action All working well.
in this Link 
http://odata.github.io/WebApi/#04-06-function-parameter-support
the author write that the OData Function Support Complex Parameter collection. In my test not.
Using native type, for example, int, string ec.. all working.

**Comment by VikingsFan** [comment] 2016-07-15 03:28
@premiaware can you tell us the dll System.Web.OData's version you are using?

and share your $metadate to us.

**Comment by premiaware** [comment] 2016-07-15 06:51
Thank's for support
Microsoft.OData.Core.dll  6.15.0.0
Microsoft.OData.Client.dll  6.15.0.0
Microsoft.OData.Edm.dll  6.15.0.0

I have Attached metadata and code.

[metadata.zip](https://github.com/OData/odata.net/files/365334/metadata.zip)
[code.zip](https://github.com/OData/odata.net/files/365342/code.zip)

**Comment by VikingsFan** [comment] 2016-07-19 06:04
@premiaware I still can't repro, your code seems right, and this is my repro, please make sure you have run the tt file and didn't manually changed the code generate result. And can you try to call the service without OData Client to see this is a Service problem or client problem.

Model:

            builder.ComplexType<Address>();

            var function = builder.Function("UnboundFunction").Returns<string>();
            function.Parameter<int>("p1");
            function.Parameter<string>("p2");
            function.CollectionParameter<Address>("locations");

Controller: 

        [HttpGet]
        [ODataRoute("UnboundFunction(p1={intP},p2={strP},locations={addP})")]
        public IHttpActionResult UnboundFunction([FromODataUri] int intP, [FromODataUri] string strP,
            [FromODataUri] IEnumerable<Address> addP)
        {
            return Ok("");
        }

Client Call:

            List<Address> addresses = new List<Address>();
            addresses.Add(new Address
            {
                Id = 1
            });

            var container = new Container(new Uri("http://localhost:9009/odata/"));
            DataServiceQuerySingle<string> ret = container.UnboundFunction(1, "2", addresses);
            string result = await ret.GetValueAsync();

Browser Call:

          http://localhost:9009/odata/UnboundFunction(p1=1,p2='2',locations=@locations)?@locations=[{%22%40odata.type%22:%22%23UnboundNS.Address%22%2C%22Id%22:1}]

**Comment by premiaware** [comment] 2016-07-25 15:01
Hello, excuse me for delay

Your code working well if the complex object is :

    public class Address
    {
        public int id { get; set; }
    }

if you change the id property from int to long type exception is generated and not working;
with this complex object crash
    public class Address
    {
        public int long { get; set; }
    }

**Comment by LaylaLiu** [comment] 2016-07-29 07:59
@premiaware Thanks for reporting this issue. It should be a client bug. when a property is of long type and used in Uri. Client will serialize it into a string with IEEE754-compatible format, but on server side, it is using IEEE754-compatible = false to read the pamameter, which caused this issue. We need to fix it.

**Comment by madansr7** [comment] 2019-10-07 21:45
Sorry for the delay in picking this up. OData client needs to serialize numeric function parameters always as IEEE754-compatible = false.

**Comment by habbes** [comment] 2019-12-03 07:47
I could not reproduce this issue.

I created a service exposing a function that accepts as a parameter a collection of complex types that includes a long property. Both the service and client class worked as expected.

**Comment by habbes** [comment] 2019-12-04 07:54
@premiaware could you check whether your issue occurs in newer versions of the library? If it does, please create a new issue. I'll close this one. Thanks.

**Closed** 2019-12-04 07:54 UTC
Labels: P2, bug, client
