### ISSUE TITLE
$select and $expand on complex subtype not working for OData API

### ISSUE THREAD

**Issue by abhaysibal** [OData/odata.net#2107] opened 2021-06-15 15:07 UTC
I am trying to expose an additional property from an existing OData API. The property is a complex type, which internally has a simple dictionary. A parent entity "Run" composes this particular entity "runProps"

### Assemblies affected

OData.Edm 7.8.3*

### Reproduce steps

This is how the complex entity has been defined:

```
<edm:ComplexType Name="runProps" OpenType="true" xmlns:edm="http://docs.oasis-open.org/odata/ns/edm">
     </edm:ComplexType>
```

This is how it is being defined inside it's parent entity:

```
<edm:Property Name="runProps" Type="org.capture.groups.runProps" Nullable="false">
         <edm:Annotation Term="Org.OData.Core.V1.Computed" Bool="true" />
       </edm:Property>
```

### Expected result

$select and $expand when passed as query options to the parent entity should fetch the child object.

### Actual result

Getting back an HTTP 500 ERRCONNRESET

### Additional detail

Can we query complex subtypes using $select and $expand, which are not navigational properties? If yes, am I missing something on the metadata?

**Comment by gathogojr** [comment] 2021-06-15 16:39
Thank you @abhaysibal for reporting this issue. Kindly share a repro that can help us reproduce the issue. If you can share the complete metadata please do.

**Comment by KenitoInc** [comment] 2022-05-18 12:23
@abhaysibal Did you manage to resolve this issue?

**Comment by KenitoInc** [comment] 2022-06-30 09:23
@abhaysibal closing this since we cannot repro

**Closed by KenitoInc** 2022-06-30 09:23 UTC
Labels: follow-up
