### ISSUE TITLE
Can't add Microsoft.Spatial nuget package in VS2017RC 

### ISSUE THREAD

**Issue by schnitty** [OData/odata.net#751] opened 2017-01-18 07:02 UTC
*Short summary (3-5 sentences) describing the issue.*  

Get an error when trying to add Microsoft.Spatial nugget package to a .NET Core project in VS2017

### Assemblies affected
*Which assemblies and versions are known to be affected e.g. OData .Net lib 6.15-beta.*  

Microsoft.Spatial 6.15.0 > Microsoft.Spatial 7.0.0

### Reproduce steps
*The simplest set of steps to reproduce the issue. If possible, reference a commit that demonstrates the issue.*  

```
PM> Install-Package Microsoft.Spatial -version 6.15.0
  GET https://api.nuget.org/v3/registration1-gz/microsoft.spatial/index.json
  OK https://api.nuget.org/v3/registration1-gz/microsoft.spatial/index.json 1204ms
Restoring packages for C:\Development\Sandbox\vs2017search\vs2017search\vs2017search.csproj...
Install-Package : Package Microsoft.Spatial 6.15.0 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package Microsoft.Spatial 6.15.0 supports:
  - dnx451 (DNX,Version=v4.5.1)
  - dnxcore50 (DNXCore,Version=v5.0)
  - portable-net40+sl5+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile328)
  - portable-net45+win8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile111)
At line:1 char:1
+ Install-Package Microsoft.Spatial -version 6.15.0
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : One or more packages are incompatible with .NETCoreApp,Version=v1.1.
At line:1 char:1
+ Install-Package Microsoft.Spatial -version 6.15.0
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : Package restore failed. Rolling back package changes for 'vs2017search'.
At line:1 char:1
+ Install-Package Microsoft.Spatial -version 6.15.0
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
```
 

### Expected result
*What would happen if there wasn't a bug.*  

Nuget package would be added to project and I would be able to use it

### Actual result
*What is actually happening.*  

Error saying not compatible.

### Additional details
*Optional, details of the root cause if known. Delete this section if you have no additional details to add.*

Works ok in VS2015

**Comment by brjohnstmsft** [comment] 2017-03-06 22:55
@schnitty Just to clarify, did you also reproduce this problem with Microsoft.Spatial 7.0.0?

**Comment by xiaoxin1983** [comment] 2017-03-07 03:54
I have same problem when i install "Microsoft.Spatial 7.0" use VS2017

**Comment by Toolenaar** [comment] 2017-03-16 20:37
same problem trying to add Microsoft.Azure.Search. Wont install because Microsoft.Spatial is not compatible. Any eta on this ?

**Comment by lpunderscore** [comment] 2017-03-23 01:01
yeah can confirm this as well....

**Comment by brjohnstmsft** [comment] 2017-03-23 01:28
@xiaoxin1983 @Toolenaar @lpunderscore Thanks for letting us know you're also affected by this. While I don't have a specific ETA yet, this is being actively worked on, at least on the OData side. Once there is a new version of Microsoft.Spatial available with the fix, I will update the Microsoft.Azure.Search package accordingly.

**Comment by AlanWong-MS** [comment] 2017-05-05 22:24
I was able to pull our recently released 7.2.0 libraries onto .NET Framework and .NET Core projects in Visual Studio 2017 using NuGet Package Manager. Please let me know if this still doesn't work. Thanks!

**Comment by tutike2000** [comment] 2017-05-18 09:08
Still can't install Microsoft.Azure.Search:

`Installing Microsoft.Azure.Search 4.0.0-preview.
Package Microsoft.Spatial 6.15.0 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package Microsoft.Spatial 6.15.0 supports:
  - dnx451 (DNX,Version=v4.5.1)
  - dnxcore50 (DNXCore,Version=v5.0)
  - portable-net40+sl5+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile328)
  - portable-net45+win8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile111)
One or more packages are incompatible with .NETCoreApp,Version=v1.1.`

**Comment by AlanWong-MS** [comment] 2017-05-18 17:00
No problem. I'm going to close this thread for now, but please feel free to re-open or create a new report if issue persists on the ODL 7.x branch.

**Closed by AlanWong-MS** 2017-05-18 17:00 UTC

**Comment by brjohnstmsft** [comment] 2017-05-18 22:55
@tutike2000 We're still working on getting a new Search package published that depends on the newest version of Microsoft.Spatial. It should be soon. Stay tuned.
