### ISSUE TITLE
Memory Leak in Library?

### ISSUE THREAD

**Issue by rbarten** [OData/odata.net#1145] opened 2018-04-06 07:08 UTC
We have a Windows Service which reads out messages from a MSMQ en uses the OData.Net libraries to Add and Update data in an external system. The Memory Allocation of the OData.Net is increasing fast when we do batch actions using the OData.Net libary.
Especcialy the Dictionary with LinkInfo within the 'EntityDescriptor' and the List of ODataNestedResourceInfo' with MaterializerEntry (FeedAndEntryMaterializerAdapter). (See screenshot below)
This memory is never released and after some time a few GB of memory is allocated.
Is there a way to overcome this? Or should this be fixed within the library?

### Assemblies affected

OData .Net lib 7.4.4 and earlier.

### Reproduce steps

Create an application/service which is doing a lot of CRUD actions using the library.

### Expected result

Memory Allocation should be released when DataServiceContext is disposed.

### Actual result

This memory is never released and after some time a few GB of memory is allocated.
See screenshots below when application was running for a short time:
![memory allocation1](https://user-images.githubusercontent.com/2169036/38407330-4b7f8bee-3979-11e8-8c74-c22e5df7898f.png)

![memory allocation2](https://user-images.githubusercontent.com/2169036/38407341-56ab2ef6-3979-11e8-9cd7-5871b35374d1.png)

**Comment by mprigge** [comment] 2018-04-23 16:11
I am also having a similar problem with 7.4.4 with an application written to do something similar (sync from an external source to an upstream OData API). I haven't been able to revert to 6.x.x to test that, but I'm relatively certain this became a problem after upgrading to 7.x. I can provide whatever level of detail you'd find helpful in troubleshooting.

**Comment by kgjersda** [comment] 2018-04-26 12:29
Having a similar problem. W3WP uses many gigabytes of ram.

**Comment by davidmilligan** [comment] 2018-05-07 11:31
I can also confirm this memory leak. The static dictionary in ODataAnnotatableExtensions seems to be the source of the problem (though there may be others). It looks like this bug was possibly introduced in commit 0aad86f912aa87264ad0fa98ba6596b96731cd37

**Comment by mathiasbl** [comment] 2018-05-08 13:42
I'm also noticing an increased memory usage with finally an out of memory exception.

**Comment by AartBluestoke** [comment] 2018-05-17 02:53
the old replaced code in 0aad86f had a codepath of { public void SetAnnotation(...) {
            if (annotation == null)	
            {	
                RemoveAnnotation<T>();	
            }	
...
    }
The new code has no code paths for removing annotations, and infact asserts that the request is never null, meaning that once you searilize an entity for transmistion, creating the 
...
I think i've got a fix for the issue, at https://github.com/OData/odata.net/compare/master...AartBluestoke:AartBluestoke-memleak-patch-1 , but it changes the behaviour when you set the annotation twice (which should never happen). As such this change doesn't meet the criteria for a PR,  but i think that this can be resolved either by finding and re-enabling the set-null path (which may be hard to do safely due to no knowing who holds references) or by using the ConditionalWeakTable as suggested by the linked code.

**Comment by davidmilligan** [comment] 2018-05-19 01:41
I'm not sure why 0aad86f can't basically just be reversed. I don't really understand the purpose of it and it seems kind of silly to me the way it was implemented. Two public instance methods were replaced with internal extension methods. Why not simply make the instance methods internal and leave them as instance methods? Then you don't have to use an ephemeron to store the data without a memory leak. The implementation also uses a generic static class which seems a bit sketchy to me.

The original implementations of the instance methods could be improved quite a bit too, not sure why they were using a plain object array and doing all that casting. A dictionary keyed by `Type` would be much simpler and faster.

For now, we have reverted to 6.19 until this issue is fixed (and we really need it fixed b/c we need some of the newer features in 7.x like ignoring properties)

**Comment by AartBluestoke** [comment] 2018-05-24 23:15
@davidmilligan given the current code structure with the asserts that a null assignment never happens, a reversion will not do anything about the memory leak - un-assignment never happens; and given how the lifetime of the annotation needs to be tied to the lifetime of the annotated object, and that a) the annotated object doesn't know it has been annotated to clean itself up, and b) the annotator doesn't know the lifetime of the annotated object, i believe the only reasonable solution is to use some type of weak-reff or other memory aware collection, for which the only native construct that i'm aware of is ConditionalWeakTable. ( i'll propose this as a pr shortly)

**Comment by davidmilligan** [comment] 2018-05-25 02:52
@AartBluestoke I’m sorry but you are wrong. Reverting the commit will fix the issue. I can confirm that it does.

This issue here is that you have annotatable objects needing to reference annotation objects. The normal way for object A to reference object B is to let object A have a field with a reference to B. Once all references *to* A have gone out of scope, A will be garbage collected (even if it contains a reference to B, and even if there are other references to B preventing it from going out of scope). If instead of associating A and B by using a field, you use a static dictionary with A as a key, A will be permanently rooted (and so will B). You can avoid this problem by using an ephemeron, which is a special type of dictionary that basically has weak references for keys. These are typically employed whenever you need to give some object a reference to another, but you don’t control the definition of the class and can’t simply add a field (this is a common sort of thing a compiler would need to do which is why there’s an ephemeron implementation in the “CompilerServices” namespace). 

However, the much simpler solution here is to simply have A reference B itself using a field (since we control the definition of A). Which is how the code was before this commit and that is why reverting it will fix the issue. 

I’m not saying your fix won’t work, but I think it makes a lot more sense to simply revert the commit and use “normal” fields to store the annotations, rather than some sort of complicated weak dictionary.

**Comment by kgjersda** [comment] 2018-06-12 08:09
The difference can be staggering, we have a small service that prints som documents.

With memory leak:
![image](https://user-images.githubusercontent.com/5937901/41277853-a6546ac4-6e28-11e8-888e-0c8cf00dfca0.png)

Without memory leak, 6.19:
![image](https://user-images.githubusercontent.com/5937901/41277818-94f6f5b2-6e28-11e8-8847-be3d990bf68b.png)

**Comment by jwobbeoya** [comment] 2018-06-12 14:39
How on earth is this a P3?  In order to avoid multiple outages / day with the 7.x client, we now have to recycle our application pools 5 - 10 times per day.  This is an ugly workaround and is definitely impacting our customers.  This issue deserved more attention.  Take a look a the P1 list: https://github.com/OData/odata.net/labels/P1

**Comment by AlanWong-MS** [comment] 2018-06-25 23:07
All, we've merged @AartBluestoke's proposed change and have the code in our [nightly build](https://www.myget.org/feed/odlnightly/package/nuget/Microsoft.OData.Client). I am currently reviewing the change; in the meantime, can anyone help with verifying that the fix addressed the issue in their test environment?

**Comment by rbarten** [comment] 2018-06-26 19:17
@AlanWong-MS @mikepizzo I did a test with the nightly build and the issue is fixed for me. The memory usage is stable. Is there an indication on when OData Lib 7.5 will be released?

**Comment by mikepizzo** [comment] 2018-06-26 20:02
Thanks for the quick follow-up @rbarten. We are working on the 7.5 release now, and confirmation that this issue was fixed was one of the last remaining items.

**Closed by mikepizzo** 2018-06-26 20:02 UTC
Labels: P1
