### ISSUE TITLE
OData Client that doesn't require client-proxy classes generation?

### ISSUE THREAD

**Issue by Patricia-Dieguez** [OData/odata.net#1251] opened 2018-09-12 10:55 UTC
Hi,
We are currently working on a AspNet Core project that access OData services. Our "issue" is that the metadata info provided is constantly updated (new entities and fields are constantly added or removed) so generating the C# client-proxy classes every time it changes (we don't even know when those changes happens) is not viable. 

We would need something more dynamic that wouldn't require those client-proxy classes to be generated (like for instance the Simple.OData.Client library: https://github.com/object/Simple.OData.Client).
Is there any plan by Microsoft to develop something like this or improve the current OData Client Code Generator library to work in a more dynamic way?

Many thanks,
Patricia Dieguez
Thermo Fisher Scientific - The world leader in serving science

**Comment by julealgon** [comment] 2018-10-08 19:26
I'm trying to use `DataServiceContext` class with a simple POCO in the client side and I'm facing errors like:
> The complex type 'System.Object' has no settable properties.

I found this other very old issue that also described a similar problem: https://github.com/OData/odata.net/issues/325

I'm not entirely sure if your proposal and my problem are related, but the fact of the matter is that I just can't use `DataServiceContext` to call my API and have to rely on SimpleOData.Client as well (which works perfectly as far as I could tell).

Could someone from the OData team please advise here?

**Comment by NetTecture** [comment] 2018-10-26 12:43
As a workaround you can use Simple.Odata.CLient (as you indicated), but do not expect it to work with anything action wise that is more complex than simple parameters as THIS library (which is used internally) has serious problems handling that (#1304 i.e.). It works with standard cases, though, and it allows you to reuse a shared library of entity/complex type objects. This is what we do - no way I regenerate client objects, especially not as I already have them separated in a separate library ;)

There is no other way. I do not see MS coming forward here - odata is getting very few updartes in between and there are already some major client side reworkings for rest in the dotnetcore framework scheduled.

**Comment by godrage** [comment] 2018-11-09 10:00
After extensive tests with both clients (simple Odata vs microsoft.odata):

-simple odata: performs horrible, especially with large models
-simple odata: requires no client proxy and is 'simple' which is favorable as it allows to write requests in string and more natural

so as long as you have a relatively small edm model, simple odata does astonishingly well.

imho the downfall you have in general is change-tracking for the PATCH statement, where javascript clients excel (without type anchoring, just using bound properties) but c# has to utilize observable collections and EF-change-tracking mechanisms.

**Comment by robertmclaws** [comment] 2018-11-09 16:47
Honestly, I feel like a brand new OData client is needed at this point. I feel like there is a lightweight way to be able to do Batching and Patching without the heavy and error-prone mechanisms we've seen in the past. Many of these libraries re-generate objects that are already generated by other frameworks, and reflection plus lightweight tracking mechanisms should be able to handle it.

Part of the problem is that the OData ecosystem is so far out of date, and there is too much that needs to be done. I would LOVE to be able to create a Client that had identical .NET Standard and TypeScript implementations that supported zero-codegen and batching/patching. I don't know that we should rely on Microsoft to make this happen... they have too much to do fixing OData to run on .NETFX and .NETCore.

**Comment by marabooy** [comment] 2020-02-19 16:11
@PDNemesis the client should be able to work in this way( without using codegen) by using the dataservice context.

An example is.
```
public class Person
{
        public string Id { get; set; }
        public string UserName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
}
// Dataservice context
 public class Container : DataServiceContext
{
 public Container(Uri serviceRoot) : 
                base(serviceRoot)
        {
              this.People = base.CreateQuery<Person>("People");
              this.Format.LoadServiceModel= ()=>{your method that returns a parsed Csdl}
              this.Format.UseJson(); /// makes sure the model is loaded so you can use this isntance of the container in your DI container
        }
   public DataServiceQuery<Person> People {get; private set;}
}

...
// usage
var context = new Container(uri);
var people= context.People;

 foreach (var person in people)
 {
           Console.WriteLine(person.UserName);
  }
```

**Comment by marabooy** [comment] 2020-02-28 07:21
@PDNemesis the docs for this have been added in https://github.com/MicrosoftDocs/OData-docs/pull/111.

**Comment by marabooy** [comment] 2020-02-28 07:23
@Patricia-Dieguez Kindly do feel free to reopen the issue if the above sample doesn't work. We have also opened a PR for documenting how to use the DSC without codegen.

**Comment by A9G-Data-Droid** [comment] 2022-03-17 20:44
While looking for a solution to this problem I found the document cited here: https://docs.microsoft.com/en-us/odata/client/using-poco-classes

**Comment by KenitoInc** [comment] 2022-08-18 10:54
With this documentation https://docs.microsoft.com/en-us/odata/client/using-poco-classes
We can close the issue

**Closed by KenitoInc** 2022-08-18 10:54 UTC
Labels: question, client

**Comment by godrage** [comment] 2022-10-11 09:44
this leaves a lot of questions unanswered such as change tracking, batch and the implementation of custom actions and functions -- will the  'LoadServiceModel' method basically implement all serverside actions,functions and models? how would you call them in the client without defining them? would greatly appreciate more documentation, samples or a best practice. also is the intended use only while developing as described in the article?

**Comment by A9G-Data-Droid** [comment] 2022-10-11 15:25
@godrage it really depends on what you are doing. My main need was to be able to query any table, display that table to a user. Let the user interact with the data, then upload the changes back to the server. That sort of dynamic workflow should by 100% automatic, with no pre-defined code generation.

If you are calling API functions then you absolutely need to know what those are ahead of time. You also need to know when breaking changes occur on the API. If the service advertises a swagger interface then those APIs could absolutely be mapped on the fly but that's not OData. That's a totally different tech stack: https://github.com/swagger-api/swagger-codegen

**Comment by maraboomint** [comment] 2022-10-12 08:37
@godrage Is there a reason you would like to not use the codegen? The codegen should provide you with all the above features plus any new features that will be introduced to the client.

**Comment by maraboomint** [comment] 2022-10-12 08:37
@godrage Is there a reason you would like to not use the codegen. The codegen should provide you with all the above features plus any new features that will be introduced.

**Comment by marabooy** [comment] 2022-10-12 08:40
@godrage Is there a reason you would like to not use the codegen. The codegen should provide you with all the above features plus any new features that will be introduced.

**Comment by godrage** [comment] 2022-10-14 08:26
the reason we would prefer to avoid the code-gen is efficiency-based and security-based.
the less information about server-side endpoints are in a client, the better - from our point of view.
we also had to customize half the codegen as our client model deviates from our server model in terms of embedded ui functionality (IDataErrorInfo, IEditableObjects, INotifyPropertyChanged, etc.) - which is also one of the reasons we think that server-side models deviate from client-side models too vastly to use partials

---- a lot is basically our perference and the less dependencies, the better for us in the long-term and management
