### ISSUE TITLE
Response serialization fails when $expand is used in conjunction with $select that excludes key and / or concurrency properties.  

### ISSUE THREAD

**Issue by korygin** [OData/odata.net#633] opened 2016-07-11 14:32 UTC
_Short summary (3-5 sentences) describing the issue._  

When using $expand query option with $select which excludes key and / or concurrency properties,
the response fails with "The entity instance value of type 'ODataRoutingDemo.Models.Discipline' doesn't have a value for property 'Id'. To compute an entity's metadata, its key and concurrency-token property values must be provided." error.
### Assemblies affected

Microsoft.OData.Core.dll
### Reproduce steps

_The simplest set of steps to reproduce the issue. If possible, reference a commit that demonstrates the issue._  

The sample project is attached, use the following query to see the problem:
http://localhost:1861/Projects(1)/Disciplines(1)?$select=Name&$expand=Attributes

[ODataRoutingDemo.zip](https://github.com/OData/odata.net/files/357286/ODataRoutingDemo.zip)
### Expected result

The response that includes selected and expanded properties should be returned to the client
### Actual result

The response fails with the following error:
{
error: {
code: "",
message: "An error has occurred.",
innererror: {
message: "The entity instance value of type 'ODataRoutingDemo.Models.Discipline' doesn't have a value for property 'Id'. To compute an entity's metadata, its key and concurrency-token property values must be provided.",
type: "Microsoft.OData.Core.ODataException",
stacktrace: " at Microsoft.OData.Core.Evaluation.ODataEntryMetadataContext.GetPrimitivePropertyClrValue(ODataEntry entry, String propertyName, String entityTypeName, Boolean isKeyProperty) at Microsoft.OData.Core.Evaluation.ODataEntryMetadataContext.<>c__DisplayClass2.<GetKeyProperties>b__0(IEdmStructuralProperty p) at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext() at System.Linq.Buffer`1..ctor(IEnumerable`1 source) at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source) at Microsoft.OData.Core.Evaluation.ODataEntryMetadataContext.GetKeyProperties(ODataEntry entry, ODataFeedAndEntrySerializationInfo serializationInfo, IEdmEntityType actualEntityType) at Microsoft.OData.Core.ODataWriterCore.EnterScope(WriterState newState, ODataItem item) at Microsoft.OData.Core.ODataWriterCore.WriteStartNavigationLinkImplementation(ODataNavigationLink navigationLink) at Microsoft.OData.Core.ODataWriterCore.WriteStart(ODataNavigationLink navigationLink) at System.Web.OData.Formatter.Serialization.ODataEntityTypeSerializer.WriteExpandedNavigationProperties(IDictionary`2 navigationPropertiesToExpand, EntityInstanceContext entityInstanceContext, ODataWriter writer) at System.Web.OData.Formatter.Serialization.ODataEntityTypeSerializer.WriteEntry(Object graph, ODataWriter writer, ODataSerializerContext writeContext, IEdmTypeReference expectedType) at System.Web.OData.Formatter.Serialization.ODataEntityTypeSerializer.WriteObjectInline(Object graph, IEdmTypeReference expectedType, ODataWriter writer, ODataSerializerContext writeContext) at System.Web.OData.Formatter.Serialization.ODataEntityTypeSerializer.WriteObject(Object graph, Type type, ODataMessageWriter messageWriter, ODataSerializerContext writeContext) at System.Web.OData.Formatter.ODataMediaTypeFormatter.WriteToStream(Type type, Object value, Stream writeStream, HttpContent content, HttpContentHeaders contentHeaders) at System.Web.OData.Formatter.ODataMediaTypeFormatter.WriteToStreamAsync(Type type, Object value, Stream writeStream, HttpContent content, TransportContext transportContext, CancellationToken cancellationToken) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter.GetResult() at System.Web.Http.Owin.HttpMessageHandlerAdapter.<BufferResponseContentAsync>d__13.MoveNext()"
}
}
}
### Additional details

_Optional, details of the root cause if known. Delete this section if you have no additional details to add._

**Comment by TomDu** [comment] 2016-08-03 03:17
Hi @korygin , this is a bug which happens when $select non-key properties and $expand a navigation property of contained entity type, we will fix it and thanks a lot for your feedback.

**Comment by korygin** [comment] 2018-03-28 20:58
Hello, any estimate on when this issue is going to be fixed? Thanks!

**Comment by sixlettervariables** [comment] 2018-09-27 16:44
I'm on OData 7.X and still see this issue. Was this supposed to be fixed in 6.X?

**Comment by gogulsekar** [comment] 2019-03-13 10:20
+1

**Comment by undercon** [comment] 2019-04-25 11:52
I am also facing this and would like to note two things:

a) I face it with a url like http://localhost:1861/Projects?$expand=Disciplines($select=Name;$expand=Attributes), which also fails with the same error response in this project as well, as do all similar situations.
b) The service at https://services.odata.org/V4/OData/OData.svc/ does not manifest this behavior.
e.g. https://services.odata.org/V4/OData/OData.svc/Suppliers(0)/Products?$expand=Categories($select=Name;$expand=Products) works fine
What is different there? 

I'm using OData 7.5.4

**Comment by VenuMadhavPerumalla** [comment] 2020-02-21 19:00
@TomDu - Please let me know when if there's a timeline for the fix

**Comment by StevenLiekens** [comment] 2020-08-26 09:22
This bug still manifests itself in OData 7.7.0, can this get more attention?

**Comment by rdhainaut** [comment] 2021-01-15 22:28
I m using ODATA Microsoft.AspNetCore.OData 7.5.4
I m a big fan of OData with Asp.net (core) but i have encountered a frustrating random bug where I was totally disappointed...
I have found this issue on google and It seems that s match
Indeed after a lot of isolation and try /error => It occurs only when I request 2 concurrency GET ODATA api calls AND when I use $select + $expand in the REST URL.

I have an 400 error response  (for one odata call only) => 
`"The query specified in the URI is not valid. The property 'xxx' cannot be used in the $expand query option."`
The error message is confusing because $expand works properly (i have tested GET ODATA call with 100 % success if it s called alone)

Backend code
```
        // In MyOData controller
        [EnableQuery]
        public IQueryable<MyEntity> Get()
        {
            return _myService.Queryable().AsNoTracking();
        }
```

ODATA GET Rest URL (I try to minimize the payload)
```
   https://Domain.Extension/odata/OneEntity?$select=field1, field2 // The first REST URL 
   https://Domain.Extension/odata/OtherEntity?$expand=NavigationProperty($select=fieldA,fieldB) // The second REST URL
```

The bug is random and so it s difficult to reproduce / debug.
When i am in debug on Visual studio I have zero error (so frustrating)

The bug is gone when 
 - I remove $select (from OneEntity GET call)
 Or 
 - I remove $expand (From OtherEntity GET call)

**Comment by orbus-dkreivenas** [comment] 2021-02-24 15:56
We also experiencing this issue, as a potential workaround I have written this `GetQueryStringForContainedTypes` extension that is called OnActionExecuting, by extending the EnableQuery attribute, it returns a rebuilt query string that then can be reapplied to the HttpRequest.QueryString, 

If you are using query options other than $select, $extend, $top, $skip, $filter and $orderby they will be removed from the query string, but it should be easy to extend this if needed, hope it helps.

```C#
/// <summary>
    /// Extension methods for <see cref="ODataUriParser"/>.
    /// </summary>
    public static class ODataUriParserExtensions
    {
        /// <summary>
        /// Retrives a <see cref="QueryString"/> ensuring that PrimaryKey of Source Entity
        /// is included in the $select query for Contained Types.
        /// </summary>
        /// <param name="parser"><see cref="ODataUriParser"/>.</param>
        /// <param name="request"><see cref="HttpRequest" />.</param>
        /// <returns><see cref="QueryString"/>.</returns>
        public static QueryString GetQueryStringForContainedTypes(this ODataUriParser parser, HttpRequest request)
        {
            var selectedItems = parser.ParseSelectAndExpand().SelectedItems;

            // Add primary keys for contained relationships
            var expandSelect = CheckItems(parser, selectedItems);

            // Update QueryString
            var query = QueryHelpers.ParseQuery(request.QueryString.ToString());

            if (expandSelect.selectItems.Any())
            {
                query["$select"] = new StringValues(expandSelect.selectItems.ToArray());
            }

            if (expandSelect.expandItems.Any())
            {
                query["$expand"] = new StringValues(expandSelect.expandItems.ToArray());
            }

            var qb = new QueryBuilder(query.Select(e => new KeyValuePair<string, string>(e.Key, e.Value)));

            return qb.ToQueryString();
        }

        private static (List<string> selectItems, List<string> expandItems) CheckItems(ODataUriParser parser, IEnumerable<SelectItem> selectedItems)
        {
            var selectItems = new List<string>();
            var expandItems = new List<string>();

            foreach (var item in selectedItems)
            {
                if (item is PathSelectItem pathSelectItem)
                {
                    // build select clause
                    selectItems.AddRange(pathSelectItem.SelectedPath.Select(e => e.Identifier));

                    var selectItem = CheckLevel(selectedItems, pathSelectItem);
                    if (selectItem != null)
                    {
                        selectItems.AddRange(selectItem);
                    }
                }
                else if (item is ExpandedNavigationSelectItem expandItem)
                {
                    // build expand clause
                    var identifier = expandItem.PathToNavigationProperty.First().Identifier;
                    if (expandItem.SelectAndExpand.AllSelected)
                    {
                        expandItems.Add(identifier);
                    }
                    else
                    {
                        // parse the nested select and expand
                        var expandSelect = CheckItems(parser, expandItem.SelectAndExpand.SelectedItems);

                        // handle select
                        var select = expandSelect.selectItems.Any() ? $"$select={string.Join(",", expandSelect.selectItems)}" : null;
                        var odataQuery = select ?? null;

                        // handle expand
                        var expand = expandSelect.expandItems.Any() ? $"$expand={string.Join(",", expandSelect.expandItems)}" : null;
                        AppendQueryValue(ref odataQuery, expand);

                        // handle top
                        if (expandItem.TopOption.HasValue)
                        {
                            AppendQueryValue(ref odataQuery, $"$top={expandItem.TopOption.Value}");
                        }

                        // handle skip
                        if (expandItem.SkipOption.HasValue)
                        {
                            AppendQueryValue(ref odataQuery, $"$skip={expandItem.SkipOption.Value}");
                        }

                        // handle count
                        if (expandItem.CountOption.HasValue)
                        {
                            AppendQueryValue(ref odataQuery, "$count=true");
                        }

                        var path = parser.ParsePath();

                        // handle filter
                        if (expandItem.FilterOption != null)
                        {
                            var odataUri = new ODataUri
                            {
                                Path = path
                            };
                            odataUri.Filter = expandItem.FilterOption;

                            var query = odataUri.GetQueryString();

                            if (query != null)
                            {
                                AppendQueryValue(ref odataQuery, query);
                            }
                        }

                        // handle order by
                        if (expandItem.OrderByOption != null)
                        {
                            var odataUri = new ODataUri
                            {
                                Path = path
                            };
                            odataUri.OrderBy = expandItem.OrderByOption;

                            var query = odataUri.GetQueryString();

                            if (query != null)
                            {
                                AppendQueryValue(ref odataQuery, query);
                            }
                        }

                        expandItems.Add($"{identifier}({odataQuery})");
                    }
                }
            }

            return (selectItems, expandItems);
        }

        private static IEnumerable<string> CheckLevel(IEnumerable<SelectItem> allItems, PathSelectItem pathSelectItem)
        {
            var containedNavigations = pathSelectItem.SelectedPath.OfType<NavigationPropertySegment>().Where(e => e.NavigationProperty.ContainsTarget);
            var primaryKeys = containedNavigations.SelectMany(e => (e.NavigationProperty.DeclaringType as EdmEntityType).DeclaredKey.Select(e => e.Name));
            var propertySegments = allItems.OfType<PathSelectItem>().SelectMany(e => e.SelectedPath.OfType<PropertySegment>().Select(e => e.Property.Name));
            var hasPrimaryKeySelected = primaryKeys.All(k => propertySegments.Contains(k));

            if (containedNavigations.Any() && !hasPrimaryKeySelected)
            {
                return primaryKeys;
            }

            return null;
        }

        private static void AppendQueryValue(ref string query, string value)
        {
            if (value == null)
            {
                return;
            }

            if (query == null)
            {
                query += value;
            }
            else
            {
                query += $";{value}";
            }
        }

        private static string GetQueryString(this ODataUri odataUri)
        {
            var uri = odataUri.BuildUri(ODataUrlKeyDelimiter.Parentheses);
            var segments = HttpUtility.UrlDecode(uri.ToString()).Split("?");
            return segments.Length > 1 ? segments[1] : null;
        }
    }
```

**Comment by habbes** [comment] 2022-04-04 08:45
Added to backlog: 1729119

**Comment by habbes** [comment] 2023-02-24 14:16
It seems like this issue occurs when you're selecting/expanding a contained navigation property and you're requesting full metadata (`odata.metadata=full` in the Accept header). Curious whether anyone has encountered this issue when not dealing with contained navigation property or when requesting minimal metadata (`odata.metadata=minimal` in the Accept header)

**Comment by habbes** [comment] 2023-03-01 03:41
@rdhainaut your issue sounds different to the OP's question. If you're getting an error that occurs randomly when making multiple concurrent requests, it could be race condition somewhere being triggered by a concurrent write to shared object by two threads. If you still face that issue when using the latest versions of the library, I suggest creating a new issue and we'll investigate it.

**Comment by habbes** [comment] 2023-03-01 03:44
Closing this issue because I have not been able to reproduce it on the latest ODL and web API versions when using the minimal metadata. If someone faces the issue again in the latest versions, or if someone needs support for `$select` and `$expand` through contained navigation properties when requesting full metadata (`odata.metadata=full`) without selecting the ID field, I suggest opening a new issue.

**Closed by habbes** 2023-03-01 03:44 UTC
Labels: bug, P2, backlog
