### ISSUE TITLE
Unable to get stream

### ISSUE THREAD

**Issue by norcino** [OData/odata.net#1693] opened 2020-03-05 12:10 UTC
I am not sure this is the right place to raise this issue because I think this might be related to Microsoft.Odata.Client, which afaik is not in Github.

My problem is described here: https://stackoverflow.com/questions/60541935/odata-client-getreadstreamasync-not-working

The GetReaStreamAsync is not working because it cannot determine the stream link, but my api is returning the metadata correctly and the hyperlinks are available in the response of the get by id request for the entity I want to download the stream for.

Any advice?

**Comment by marabooy** [comment] 2020-03-06 08:07
@norcino Closing this as it appears to be a duplicate of #1692

**Closed by marabooy** 2020-03-06 08:07 UTC
