### ISSUE TITLE
Error "Could not load file or assembly System.Linq " when deploy application desktop using Microsoft.ODataClient

### ISSUE THREAD

**Issue by herryyannara** [OData/odata.net#1499] opened 2019-07-06 09:06 UTC
I try to use OData Client Generator using odata service from Trippin Service [https://services.odata.org/V4/(S(v35us2ydb4upkphl4id2qpwx))/TripPinServiceRW/](url), create a simple application to pull AirLines data. In development was great. Now when publish with click once on Visual Studio 2017, .Net Framework 4.6.1 and deploy to client fresh OS Win 7 + Framework 4.6.1 , error occurred

System.TypeInitializationException: The type initializer for 'ClientEdmModelCache' threw an exception. ---> System.BadImageFormatException: Could not load file or assembly 'System.Linq, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context. (Exception from HRESULT: 0x80131058) ---> System.BadImageFormatException: Cannot load a reference assembly for execution.
   --- End of inner exception stack trace ---
   at Microsoft.OData.Edm.Vocabularies.EdmDirectValueAnnotationsManager.SetAnnotation(IEnumerable`1 immutableAnnotations, Object& transientAnnotations, String namespaceName, String localName, Object value)
   at Microsoft.OData.Edm.Vocabularies.EdmDirectValueAnnotationsManager.SetAnnotationValue(IEdmElement element, String namespaceName, String localName, Object value, VersioningDictionary`2& annotationsDictionary)
   at Microsoft.OData.Edm.Vocabularies.EdmDirectValueAnnotationsManager.SetAnnotationValue(IEdmElement element, String namespaceName, String localName, Object value)
   at Microsoft.OData.Edm.ExtensionMethods.SetAnnotationValue(IEdmModel model, IEdmElement element, String namespaceName, String localName, Object value)
   at Microsoft.OData.Edm.ExtensionMethods.SetEdmVersion(IEdmModel model, Version version)
   at Microsoft.OData.Client.DataServiceContext.ClientEdmModelCache.CreateClientEdmModelCache()
   at Microsoft.OData.Client.DataServiceContext.ClientEdmModelCache..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.OData.Client.DataServiceContext.ClientEdmModelCache.GetModel(ODataProtocolVersion maxProtocolVersion)
   at Microsoft.OData.Client.DataServiceContext..ctor(Uri serviceRoot, ODataProtocolVersion maxProtocolVersion)
 

### Assemblies affected

Microsoft.OData.Client.dll 7.5.1.20914 with runtime version v4.0.30319

### Reproduce steps

create simple project, add OData Client Generator, add button and list box.
`private void button1_Click(object sender, EventArgs e){`
`var container = new DefaultContainer(new Uri("https://services.odata.org/V4/(S(v35us2ydb4upkphl4id2qpwx))/TripPinServiceRW/"));`
`var stores = container.Airlines.ToList();`
`foreach (var item in stores){`
`listBox1.Items.Add(item.AirlineCode + " - " + item.Name);}`

### Additional detail

Microsoft.Odata.Client, Microsoft.Odata.Core, Microsoft.Odata.EDM, Microsoft.Spatial was successful register in GAC

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
DXApplication1
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Test/AppData/Local/Apps/2.0/O5TKPZ6V.LWJ/V5C445PZ.6YQ/dxap..tion_8a18656ab29985bc_0001.0000_5141f09b14d3282f/DXApplication1.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
DevExpress.BonusSkins.v19.1
    Assembly Version: 19.1.3.0
    Win32 Version: 19.1.3.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/DevExpress.BonusSkins.v19.1/v4.0_19.1.3.0__b88d1754d700e49a/DevExpress.BonusSkins.v19.1.dll
----------------------------------------
DevExpress.Utils.v19.1
    Assembly Version: 19.1.3.0
    Win32 Version: 19.1.3.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/DevExpress.Utils.v19.1/v4.0_19.1.3.0__b88d1754d700e49a/DevExpress.Utils.v19.1.dll
----------------------------------------
DevExpress.Data.v19.1
    Assembly Version: 19.1.3.0
    Win32 Version: 19.1.3.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/DevExpress.Data.v19.1/v4.0_19.1.3.0__b88d1754d700e49a/DevExpress.Data.v19.1.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
DevExpress.XtraLayout.v19.1
    Assembly Version: 19.1.3.0
    Win32 Version: 19.1.3.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/DevExpress.XtraLayout.v19.1/v4.0_19.1.3.0__b88d1754d700e49a/DevExpress.XtraLayout.v19.1.dll
----------------------------------------
DevExpress.XtraEditors.v19.1
    Assembly Version: 19.1.3.0
    Win32 Version: 19.1.3.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/DevExpress.XtraEditors.v19.1/v4.0_19.1.3.0__b88d1754d700e49a/DevExpress.XtraEditors.v19.1.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
System.ComponentModel.DataAnnotations
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.DataAnnotations/v4.0_4.0.0.0__31bf3856ad364e35/System.ComponentModel.DataAnnotations.dll
----------------------------------------
UIAutomationClient
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/UIAutomationClient/v4.0_4.0.0.0__31bf3856ad364e35/UIAutomationClient.dll
----------------------------------------
Microsoft.OData.Client
    Assembly Version: 7.6.0.30605
    Win32 Version: 7.6.0.30605
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.OData.Client/v4.0_7.6.0.30605__31bf3856ad364e35/Microsoft.OData.Client.dll
----------------------------------------
Microsoft.OData.Core
    Assembly Version: 7.6.0.30605
    Win32 Version: 7.6.0.30605
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.OData.Core/v4.0_7.6.0.30605__31bf3856ad364e35/Microsoft.OData.Core.dll
----------------------------------------
System.Runtime
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.dll
----------------------------------------
Microsoft.OData.Edm
    Assembly Version: 7.6.0.30605
    Win32 Version: 7.6.0.30605
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.OData.Edm/v4.0_7.6.0.30605__31bf3856ad364e35/Microsoft.OData.Edm.dll
----------------------------------------
System.Collections
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Collections/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Collections.dll
----------------------------------------
System.Threading
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Threading/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Threading.dll
----------------------------------------

**Comment by robertmclaws** [comment] 2019-07-06 23:10
You likely need to check the assemblyBinding redirects in your client app to point to the most current version of the System.Linq NuGet package.

**Comment by herryyannara** [comment] 2019-07-06 23:24
Robert, the project client app use a latest version of odata.client, and i have no idea how to check assembly binding for system.linq, because when i chek my references project it's only reference to Microsoft.odata.client, .core, .edm and.spatial. when published with click once at application file section contain only 4 reference + .tt file + exe. I could found system.linq

**Comment by robertmclaws** [comment] 2019-07-07 14:09
Either your web.config or app.config have text references to that file. Yuo can download the BindingRedirects Doctor Visual Studio add-in to try to clean up the references, or you can manually remove the entry and see if that works. You can Google "Assembly Binding Redirects" and you will get useful information on how they work. I hope that helps!

**Comment by KanishManuja-MS** [comment] 2019-07-31 21:34
@herryyannara Let us know if Robert's suggestion helped so that we can close this.

**Comment by gathogojr** [comment] 2022-03-13 19:46
Issue not reproducible in current Microsoft.OData.Client 7.10.0. No activity recorded by the issue creator since Aug 1, 2019

**Closed by gathogojr** 2022-03-13 19:46 UTC
Labels: client
