### ISSUE TITLE
ODataException is thrown when getting a worksheet range via Microsoft.Graph API

### ISSUE THREAD

**Issue by Kizuto3** [OData/odata.net#2889] opened 2024-03-07 12:34 UTC
I am trying to get a worksheet range using Simple.OData.Client NuGet package v.6.0.1 (https://github.com/simple-odata-client/Simple.OData.Client) via microsoft.graph API, however I get an ODataException with a message "The context URI '$metadata#workbookRange' references the entity set or type 'workbookRange'. However, no entity set or type with name 'workbookRange' is declared in the metadata.". After investigating the issue I found that the root of the issue is on Microsoft.OData side (please refer to Additional details section). I attached the metadata file (workbookRange_metadata.txt). Alternatively it can be received via following link: https://graph.microsoft.com/v1.0/$metadata#workbookRange
[workbookRange_metadata.txt](https://github.com/OData/odata.net/files/14524022/workbookRange_metadata.txt)

### Assemblies affected

Microsoft.OData.Edm since at least 7.6.1.30930

### Reproduce steps

```
		var id = "<id>";
		var tableName = "<name>";

		var graphLink = $"https://graph.microsoft.com/v1.0/me/drive/items/{id}/workbook/worksheets/{tableName}/range";

		var serviceUri = new Uri(graphLink);
		var settings = new ODataClientSettings(serviceUri);
		settings.BeforeRequest += (message) =>
		{
                        // access token is received via OAuth2.0 authentication
			message.Headers.Authorization = new AuthenticationHeaderValue("Bearer", "<access_token>");
		};
		settings.IncludeAnnotationsInResults = true;
		settings.MetadataDocument = await File.ReadAllTextAsync("workbookRange_metadata.txt");

		var client = new ODataClient(settings);

		var res = await client.FindEntryAsync(graphLink).ConfigureAwait(false);
```

### Expected result

Worksheet range successfully retrieved, no exception is thrown

### Actual result

ODataException is thrown with a message "The context URI '$metadata#workbookRange' references the entity set or type 'workbookRange'. However, no entity set or type with name 'workbookRange' is declared in the metadata."

### Additional detail

After some investigation, I found that the root of the issue lies in the customTypeResolver that is passed to MetadataUtils.ResolveTypeNameForRead method in the ODataJsonLightContextUriParser.ResolveType. When EdmModelBase.FindDeclaredType is called qualifiedName parameter has value "workbookRange" and schemaTypeDictionary contains required value but with a different key: "microsoft.graph.workbookRange". Since keys don't match, FindDeclaredType returns null and ODataException is thrown.

**Comment by xuzhg** [comment] 2024-03-12 15:59
@Kizuto3 Thanks for reporting this issue. 

First, Simple.OData.Client is not owned by us. We have the Microsoft.OData.Client nuget package, can you also try it? 
Second, OData type name is unique using full-qualified name. So, would you please check whether to call 'ResolveTypeNameForRead' and why the 'type name' is un-qualified?

**Comment by mikepizzo** [comment] 2024-03-12 17:49
I confirmed that Microsoft Graph API returns a contextUrl with the unqualified type name when calling `https://graph.microsoft.com/v1.0/me/drive/items/{id-of-an-excel-file}/workbook/worksheets/Sheet1/range`.  This is not conformant with the OData protocol. We *may* handle this in our client library, but it's still a bug that MS Graph is returning this unqualified type name in this scenario.

Using [Graph Explorer](https://developer.microsoft.com/en-us/graph/graph-explorer) to execute the request with the `$whatin` query option shows that the response from the excel workload is writing the contextUrl with the unqualified type name.

The excel workload uses ODataLibrary, so I wanted to confirm that our library correctly writes the qualified name.

We have a test (`BuildResourceContextUriForComplexResource`) to confirm that ODataLibrary, given a type in the ODataResourceTypeContext, will return the fully qualified type name. However, in that test case the optional `serializationInfo` parameter is passed as null to the create method. If `serializationInfo` is specified with an `ExpectedTypeName`, we use that (even if the `expectedResourceType` parameter specified in the `Create` method, the serializationInfo appears to override it):

```c#
        [Fact]
        public void BuildResourceContextUriForUnqualifiedComplexResource()
        {
            var typeContext = ODataResourceTypeContext.Create( new ODataResourceSerializationInfo { ExpectedTypeName = "Address"},
                null, null, this.addressType, throwIfMissingTypeInfo: false);
            foreach (ODataVersion version in Versions)
            {
                var contextUri = this.CreateEntryContextUri(typeContext, version, true);
                Assert.Equal(contextUri.OriginalString, BuildExpectedContextUri("#TestModel.Address"));
            }
        }
```

So, it appears that the Excel workload is creating the ODataResourceTypeContext with an ODataResourceSerializationInfo that has an unqualified ExpectedTypeName. We should make them aware of this issue, but they may not be able to fix it due to backward compatibility.

**Comment by gathogojr** [comment] 2024-03-13 12:02
@Kizuto3 @mikepizzo 
I tried to reproduce the issue reported by the customer using **Microsoft.OData.Client** and I found out because of the value returned as `@odata.context` - with type name unqualified, an exception is thrown from **Microsoft.OData.Core** `TypeUtils.ParseQualifiedTypeName` method:
![image](https://github.com/OData/odata.net/assets/28291332/4b8707c4-a9fc-49a7-822b-aaa55083ccf6)

I'll create a ticket to enhance the code in ODL to throw a more descriptive error [in place of `length ('-1') must be a non-negative value. (Parameter 'length'). Actual value was -1.`] if the type is not fully qualified.

I'll also reach out to the workload so the context Url can be fixed

**Comment by Kizuto3** [comment] 2024-03-15 09:24
I believe I discovered another issue with Microsoft Graph API.
I am getting an Microsoft.OData.ODataException with a message "_A node of type 'StartArray' was read from the JSON reader when trying to read the contents of the property 'values'; however, a 'StartObject' node or 'PrimitiveValue' node with null value was expected._" when trying to get entries from the following uri:

```
		var id = "workbook_id";
		var tableName = "<table_name>";

		var graphLink = $"https://graph.microsoft.com/v1.0/me/drive/items/{id}/workbook/tables/{tableName}/rows";
```
I am not sure if the issue is on their side and they send metadata file with invalid markup or on Microsoft.Odata side and it fails to properly parse response that contains arrays. 
Note that you have to create a table in your excel sheet first.
Here's the metadata file I am using:
[rowsMetadata.txt](https://github.com/OData/odata.net/files/14613372/rowsMetadata.txt)

Could you please look into this issue?

**Comment by gathogojr** [comment] 2024-03-26 12:25
@Kizuto3 RE: https://github.com/OData/odata.net/issues/2889#issuecomment-1999251255
That appears to be a separate issue. Please raise a fresh ticket for that otherwise the comment is very easy to miss.

**Comment by gathogojr** [comment] 2024-03-26 12:27
For the reported issue, a fix has already been rolled out.
The context URL is now returned as `https://graph.microsoft.com/v1.0/$metadata#microsoft.graph.workbookRange`.
Please try it out and report back

**Comment by gathogojr** [comment] 2024-03-29 09:35
Closing this since has since been resolved

**Closed by gathogojr** 2024-03-29 09:35 UTC
Labels: follow-up
