### ISSUE TITLE
OData FilterExpression with order of operations/parenthesis

### ISSUE THREAD

**Issue by DickvdBrink** [OData/odata.net#653] opened 2016-07-29 09:43 UTC
ODataUriParser looses information about "order of operations" when using parenthesis

Microsoft OData.Core 6.15

### Reproduce steps
```csharp
        private static IEdmModel createModel()
        {
            EdmModel model = new EdmModel();
            EdmEntityContainer container = new EdmEntityContainer("", "name");
            model.AddElement(container);

            EdmEntityType type = new EdmEntityType("", "custom");
            type.AddStructuralProperty("id", EdmPrimitiveTypeKind.Int32);
            container.AddEntitySet("custom", type);
            model.AddElement(type);

            return model;
        }

        static void Main(string[] args)
        {
            var model = createModel();
            Uri pathUri = new Uri("http://localhost/custom?$filter= 4 eq (1 add 1) mul 2", UriKind.Absolute);
            ODataUriParser uriParser = new ODataUriParser(model, new Uri("http://localhost", UriKind.Absolute), pathUri);
            var result = uriParser.ParseUri();


            Uri pathUri2 = new Uri("http://localhost/custom?$filter= 2 eq 1 add 1 mul 2", UriKind.Absolute);
            ODataUriParser uriParser2 = new ODataUriParser(model, new Uri("http://localhost", UriKind.Absolute), pathUri);
            var result2 = uriParser.ParseUri();
            // trees for result.Filter.Expression and result2 are the same
        }
```

### Expected result
Some kind of group node so I can detect parenthesis around an expression because the order of operations is different

### Actual result
Trees are the same

Same issues applies with columns ( a more real word example)

```
$filter=(id eq 1 or id eq 2) and id eq 3 // Should return an empty set

$filter=id eq 1 or id eq 2 and id eq 3 // Should return the row with id 1
```

The spec shows it being used in $search in chapter `11.2.5.6 System Query Option $search` found [here](http://docs.oasis-open.org/odata/odata/v4.0/errata03/os/complete/part1-protocol/odata-v4.0-errata03-os-part1-protocol-complete.html#ABNF)

**Comment by DickvdBrink** [comment] 2016-08-18 15:02
Any update?

**Comment by Lingxi-Li** [comment] 2016-08-19 01:41
Bug confirmed. I'm going to look into this issue.

**Comment by Lingxi-Li** [comment] 2016-08-19 01:54
@DickvdBrink, this seemingly buggy behavior is caused by typos in your sample code. Specifically, you've used `pathUri` not `pathUri2` in constructing `uriParser2`, and then called `ParseUri()` on `uriParser` instead of `uriParser2`. Addressing these two typos leads to the following code that produces the expected result :smiley:

~~~C#
EdmModel model = new EdmModel();
EdmEntityContainer container = new EdmEntityContainer("", "name");
model.AddElement(container);

EdmEntityType type = new EdmEntityType("", "custom");
type.AddStructuralProperty("id", EdmPrimitiveTypeKind.Int32);
container.AddEntitySet("custom", type);
model.AddElement(type);

Uri pathUri = new Uri("http://localhost/custom?$filter= 4 eq (1 add 1) mul 2", UriKind.Absolute);
ODataUriParser uriParser = new ODataUriParser(model, new Uri("http://localhost", UriKind.Absolute), pathUri);
var result = uriParser.ParseUri();

Uri pathUri2 = new Uri("http://localhost/custom?$filter= 2 eq 1 add 1 mul 2", UriKind.Absolute);
ODataUriParser uriParser2 = new ODataUriParser(model, new Uri("http://localhost", UriKind.Absolute), pathUri2);
var result2 = uriParser2.ParseUri();
~~~

**Comment by Lingxi-Li** [comment] 2016-08-19 02:01
I will close this issue. If you still have related problems, feel free to reopen it :)

**Closed by Lingxi-Li** 2016-08-19 02:01 UTC
Labels: feedback needed

**Comment by DickvdBrink** [comment] 2016-08-19 08:27
Hmz, sorry about the really bad sample and thanks for your answer. I thought I've seen this going wrong (that is why I created the sample). 
If I find something new I will report back. Thanks for checking!
