### ISSUE TITLE
Unable to call action with complex parameter in complex parameter.

### ISSUE THREAD

**Issue by NetTecture** [OData/odata.net#1305] opened 2018-10-26 12:47 UTC
7.5.1 - the bad tests on complex types continues, actions now totally useless outside simple usages.

Metadata first.

The following action:

```
<Action Name="BulkChange" IsBound="true">
<Parameter Name="bindingParameter" Type="Collection(PropertyCore.InspectionDuty)"/>
<Parameter Name="Updates" Type="PropertyCore.InspectionDutyChanges"/>
</Action>
```

uses complex types:

```
<ComplexType Name="InspectionDutyChanges">
<Property Name="Comment" Type="Edm.String"/>
<Property Name="Changes" Type="Collection(PropertyCore.InspectionDutyChange)"/>
</ComplexType>

<ComplexType Name="InspectionDutyChange">
<Property Name="Operation" Type="Operations.Operations" Nullable="false"/>
<Property Name="Identity" Type="Edm.Guid" Nullable="false"/>
<Property Name="IsDisabled" Type="Edm.Boolean" Nullable="false"/>
<Property Name="SeriesStart" Type="Edm.DateTimeOffset"/>
<Property Name="Interval" Type="Common.Interval"/>
<NavigationProperty Name="Module" Type="PropertyCore.Module"/>
<NavigationProperty Name="Equipment" Type="PropertyCore.Equipment"/>
<NavigationProperty Name="OperatorTask" Type="PropertyCore.OperatorTask"/>
</ComplexType>
```
Saving this change object:

```
            var change = new {
                Updates = new InspectionDutyChanges() {
                    Comment = "comment try",

                    Changes = new InspectionDutyChange [] {
                            new InspectionDutyChange() { Identity = Guid.NewGuid(), IsDisabled = false },
                            new InspectionDutyChange() { Identity = Guid.NewGuid(), IsDisabled = false },
                        },

                }
            };
```

should work. Except...

Microsoft.OData.ODataException: The parameter 'Updates' is of Edm type kind 'Complex'. You cannot call WriteValue on a parameter that is not of Edm type kinds 'Primitive', 'Enum' or 'Complex'.

Ah, yes. It is complex. it can only be complex. Exception. Nope, no.

Stack trace:

Result StackTrace:	
at Microsoft.OData.ODataParameterWriterCore.VerifyCanWriteValueParameter(Boolean synchronousCall, String parameterName, Object parameterValue)
   at Microsoft.OData.ODataParameterWriterCore.WriteValueAsync(String parameterName, Object parameterValue)

Now totally blocked - see no way to call an action that has complex parameters as this is the "last" resort, after #1304 which is not possible because complex type collections as parameters...

**Comment by biaol-odata** [comment] 2018-10-31 19:11
Likely in the same area of #1304.
@NetTecture Is this client side error also? Is there any client code you can share to repo this error? Thanks.

**Comment by xuzhg** [comment] 2018-10-31 21:49
I think it's also related to complex value. See https://github.com/xuzhg/Docs/blob/master/Docs/OData/ODataComplexValue.md

**Comment by NetTecture** [comment] 2019-01-28 14:10
Looks like. Which is open now in end of January 2019 and is a CORE element of the odata type system. Is there a chance to get this working, or shall I go and try to flatten this object hiearchy? Because sort of I have sort of customers that sort of demand odata to be working.

**Comment by PandaBoy00** [comment] 2019-04-08 00:08
It seems like the Complex Type is also producing some error whenever the type is Type="mscrm.crmbaseentity" / Type="Collection(mscrm.crmbaseentity)" / Type="Collection(mscrm.email)".  The actual correct output from use using the should be 'Property' and not 'NavigationProperty'.

Sample:
```
<ComplexType Name="AttributeAuditDetail">
	<NavigationProperty Name="OldValue" Type="mscrm.crmbaseentity" Nullable="false" />
	<NavigationProperty Name="NewValue" Type="mscrm.crmbaseentity" Nullable="false" />
	<Property Name="InvalidNewValueAttributes" Type="Collection(Edm.String)" Unicode="false" />
	<Property Name="DeletedAttributes" Type="mscrm.Collection_Int32_String" />
	<Property Name="LocLabelLanguageCode" Type="Edm.Int32" />
	<NavigationProperty Name="AuditRecord" Type="mscrm.crmbaseentity" Nullable="false" />
</ComplexType>
```
Should be:
```
<ComplexType Name="AttributeAuditDetail">
	<Property Name="OldValue" Type="mscrm.crmbaseentity" Nullable="false" />
	<Property Name="NewValue" Type="mscrm.crmbaseentity" Nullable="false" />
	<Property Name="InvalidNewValueAttributes" Type="Collection(Edm.String)" Unicode="false" />
	<Property Name="DeletedAttributes" Type="mscrm.Collection_Int32_String" />
	<Property Name="LocLabelLanguageCode" Type="Edm.Int32" />
	<Property Name="AuditRecord" Type="mscrm.crmbaseentity" Nullable="false" />
</ComplexType>
```

That is the xml output from the Transform() method in the generated ODataClient.cs produced from the T4 Template.

**Comment by NetTecture** [comment] 2019-10-15 08:53
Whow. So, a bug about a year old about a critical serialization error in the core of the EDM type system making large parts of odata useless gets removed a year later. And you wonder people are not happy with odata.

**Comment by nsarris** [comment] 2019-12-10 18:35
I traced the issue here:

https://github.com/OData/odata.net/blob/576c4ab0337bb1cecda85f4199bcc406d55b787b/src/Microsoft.OData.Core/ODataParameterWriterCore.cs#L437

The VerifyCanWriteValueParameter method checks if the parameter is of Primitive/Enum/TypeDefinition kind and if not fails with a message that says the parameter cannot be other than Primitive/Enum/Complex kind.

Either the message or the condition is wrong. If it's the latter then it's a simple fix of correcting the check.

**Comment by ysmoradi** [comment] 2020-01-05 18:25
)-:

**Comment by ysmoradi** [comment] 2020-01-05 18:37
> Whow. So, a bug about a year old about a critical serialization error in the core of the EDM type system making large parts of odata useless gets removed a year later. And you wonder people are not happy with odata.

At the moment you can use HTTP client and be sure that nothing serious is being checked in that if condition.

**Comment by paulodero** [comment] 2020-02-12 07:45
@NetTecture I have the following service with an action as follows and the action seems to be called with a complex type parameter. Please share a sample repo you used to reproduce this.

**Comment by paulodero** [comment] 2020-02-12 07:48
I have the following service with an action as follows and the action seems to be called with a complex type parameter. Please share a sample repo you used to reproduce this.

- complex types
		```
	<ComplexType Name="InspectionDutyChanges">
				<Property Name="Comment" Type="Edm.String"/>
				<Property Name="Changes" Type="Collection(ActionSample.Models.InspectionDutyChange)"/>
			</ComplexType>
			<ComplexType Name="InspectionDutyChange">
				<Property Name="Identity" Nullable="false" Type="Edm.Guid"/>
				<Property Name="IsDisabled" Nullable="false" Type="Edm.Boolean"/>
				<Property Name="SeriesStart" Nullable="false" Type="Edm.DateTimeOffset"/>
			</ComplexType>
```
- Action 
```
<Action Name="ComplexAction" IsBound="true">
				<Parameter Name="bindingParameter" Type="Collection(ActionSample.Models.Customer)"/>
				<Parameter Name="Updates" Type="ActionSample.Models.InspectionDutyChanges"/>
			</Action>
```
Client object
`
          var  Updates = new InspectionDutyChanges()
            {
                Comment = "comment try",

                Changes =  {
                            new InspectionDutyChange() { Identity = Guid.NewGuid(), IsDisabled = false },
                            new InspectionDutyChange() { Identity = Guid.NewGuid(), IsDisabled = false },
                        },

            };`

**Comment by paulodero** [comment] 2020-02-19 15:53
@NetTecture Looks like `Simple.OData.Client` library is lagging behind recent changes in OData core. `WriteValue(..)` method should not be called on complex type parameter [as implemented in Simple.OData.Client](https://github.com/simple-odata-client/Simple.OData.Client/blob/61dc9fd08e877a9e52812bce4c1d9b5e109f41ed/src/Simple.OData.Client.V4.Adapter/RequestWriter.cs#L221-L225). Microsoft.OData.Client works fine with complex type as  parameters in Actions since [complex types are treated same as Entity types](https://github.com/OData/odata.net/blob/209e434e567f67aa8220cc9682aaf2e0c2a98873/src/Microsoft.OData.Client/Serialization/Serializer.cs#L235). However the error message has been changed to avoid confusion.

**Closed** 2020-03-09 05:08 UTC
Labels: P2, client

**Comment by ysmoradi** [comment] 2020-03-09 06:43
> @NetTecture Looks like `Simple.OData.Client` library is lagging behind recent changes in OData core. `WriteValue(..)` method should not be called on complex type parameter [as implemented in Simple.OData.Client](https://github.com/simple-odata-client/Simple.OData.Client/blob/61dc9fd08e877a9e52812bce4c1d9b5e109f41ed/src/Simple.OData.Client.V4.Adapter/RequestWriter.cs#L221-L225). Microsoft.OData.Client works fine with complex type as parameters in Actions since [complex types are treated same as Entity types](https://github.com/OData/odata.net/blob/209e434e567f67aa8220cc9682aaf2e0c2a98873/src/Microsoft.OData.Client/Serialization/Serializer.cs#L235-L243). However the error message has been changed to avoid confusion.

Simple.OData.Client's issue has been fixed recently.
