### ISSUE TITLE
asp.net v5 and coreclr

### ISSUE THREAD

**Issue by grahamehorner** [OData/odata.net#264] opened 2015-07-10 17:37 UTC
please consider targeting the coreclr and/or supporting asp.net v5

**Comment by lewischeng-ms** [comment] 2015-07-13 05:20
@grahamehorner  Thanks for the suggestion. We have already supported that in ODataLib, EdmLib and Microsoft.Spatial. Please refer to #97.

**Comment by grahamehorner** [comment] 2015-07-13 07:35
@lewischeng-ms great news; are you planning to publish the nuget packages on the aspnet myget feed? and keep in sync with the release of beta packages. The reason for asking is I'd love to get odata working on the Raspberry PI v2 under dnx arm.  keep up the great work; it great to see these things evolving in public forums :+1:

**Comment by lewischeng-ms** [comment] 2015-07-13 08:37
@grahamehorner Thanks:P The reasons why we didn't put packages into aspnet myget are that: we do not have any dependency on aspnet beta packages; OData do not belong to aspnet product line. You can directly download the latest package from nuget.org to play with .net core 5. By the way, we will first close this issue. If you have any further problem, welcome to open new issues to report them:)

**Closed by lewischeng-ms** 2015-07-13 08:37 UTC

**Comment by grahamehorner** [comment] 2015-07-13 08:49
@lewischeng-ms isn't the odata controller part of the odata.net if so I would have thought is has a dependency on the aspnet mvc/api and therefore the streamlining of code in asp.net v5 and mvc 6 would have an impact? I'm currently have difficulty with asp.net beta6 and odata namespaces getting confusing etc. which version namespace package should I be referencing?

**Comment by lewischeng-ms** [comment] 2015-07-13 09:34
@grahamehorner odata.net is just a set of .NET libraries that implement OData v4 protocol. It is the **basic building block** of many OData products. One of them is called OData Web API (https://github.com/OData/WebApi) which is built upon odata.net and ASP.NET Web API (integrated into MVC 6 now) to help users easily build OData service using Web API (or MVC). The key concept of OData Web API is what you mentioned as ODataController. This kind of controller can handle OData requests.

If you would like to use odata.net in ASP.NET 5, please directly add reference to the packages (Microsoft.OData.Core, Microsoft.OData.Edm and Microsoft.Spatial) in VS2015. 

But I guess that's not your real intention. If you want to build an OData service in ASP.NET 5, you can use our latest alpha version of OData Web API (http://odata.github.io/WebApi/#07-07-6-0-0-alpha1). The alpha version was designed specifically for ASP.NET 5.

Thanks.

**Comment by grahamehorner** [comment] 2015-07-13 10:00
@lewischeng-ms many thanks for the clarification; all becomes clearer now :+1:

**Comment by lewischeng-ms** [comment] 2015-07-14 02:09
@grahamehorner You are welcome. Please don't hesitate to ask any question.
