### ISSUE TITLE
'any' operator without an argument expression throw exception

### ISSUE THREAD

**Issue by xuzhg** [OData/odata.net#2240] opened 2021-11-04 17:50 UTC
We had previously reached out to you regarding an EDM model query which we were able to resolve after having a call with you.
Recently, we have come across another issue which seems to be an OData limitation and wanted to confirm with you if there is any particular workaround available.

We have a class called Referral, in which we have an List of strings called Tags.
```C#
class Referral
{
   // ...
    List<string> Tags;
   // ...
}
```

We wish to use OData filter query to query for all entries where the tags list is empty, and are using the following odata filter query to hit our API:
GET ../referrals?$filter=tags/any()

As per documentation available online, this should return all entries where the list is empty, however we keep getting the following error:
 
![image](https://user-images.githubusercontent.com/9426627/140392642-2c8c18b1-71b6-4715-8940-bac1ab560e50.png)

For other queries such as :
GET …/referrals?$filter=tags/any (t:t eq 'OEMIoT') we get proper results and the API works as expected.

Is there any way in which we can query for an empty list in our filter query?

Be noted:
OData spec says:

```
The any operator can be used without an argument expression. 
This short form returns false if and only if the collection is empty.
```
See [here](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part2-url-conventions.html#sec_any)

**Comment by JBBianchi** [comment] 2021-11-05 11:52
I wanted to have a look so I tried to reproduce the problem in a very basic use-case (https://github.com/JBBianchi/ODataFnNotAppliable/tree/empty-any). 

There is a list with 3 elements:
- one with a list containing a tag
- one with an empty tags list
- one with no tag list

A call to `https://localhost:44328/odata/products?$filter=tags/any()` returns 1 item:
```json
{
   "@odata.context":"https://localhost:44328/odata/$metadata#Products",
   "value":[
      {
         "id":1,
         "tags":[
            "Foo"
         ],
         "name":{
            "en":"Shoe",
            "fr":"Chaussure"
         }
      }
   ]
```

Which seems to be what's expected

A call to `https://localhost:44328/odata/products?$filter=not(tags/any())` returns 1 item:
```json
{
   "@odata.context":"https://localhost:44328/odata/$metadata#Products",
   "value":[
      {
         "id":3,
         "tags":[
            
         ],
         "name":{
            "en":"Scarf",
            "fr":"\u00c9charpe"
         }
      }
   ]
}
```

Which is not what I expected as a result, knowing that the unfiltered query `https://localhost:44328/odata/products` returns:
```json
{
   "@odata.context":"https://localhost:44328/odata/$metadata#Products",
   "value":[
      {
         "id":1,
         "tags":[
            "Foo"
         ],
         "name":{
            "en":"Shoe",
            "fr":"Chaussure"
         }
      },
      {
         "id":2,
         "tags":[
            
         ],
         "name":{
            "en":"Hat",
            "fr":"Chapeau"
         }
      },
      {
         "id":3,
         "tags":[
            
         ],
         "name":{
            "en":"Scarf",
            "fr":"\u00c9charpe"
         }
      }
   ]
}
```
I expected 2 and 3 to be returned.

Another test I did is `https://localhost:44328/odata/products?$filter=tags%20eq%20null` but it results in an error `The query specified in the URI is not valid. The operand for a binary operator 'Equal' is not a single value. Binary operators require both operands to be single values.`

In any case, I was not able to reproduce the error you shared.

**Comment by xuzhg** [comment] 2021-11-05 16:54
@JBBianchi Thanks for your testing. That's helpful. 

This is an issue reported to throw email and I just copied the content from email to github. I have forwarded your comments to the customer to see what's going on.

**Comment by KenitoInc** [comment] 2021-11-10 11:52
`Any()` is supported in OData core
See a few test examples
https://github.com/OData/odata.net/blob/82d094a0f211d7394b43f2df6404d8ee5492bdb3/test/FunctionalTests/Microsoft.OData.Core.Tests/ScenarioTests/UriParser/FilterAndOrderByFunctionalTests.cs#L515-L537

**Comment by KenitoInc** [comment] 2021-12-01 08:04
We should close this @xuzhg

**Comment by ElizabethOkerio** [comment] 2022-02-16 09:25
any operator without arguments works fine. We'll add the other issues to our backlog to track them on a separate thread. Closing this issue for now but feel free to reopen it.

**Closed by ElizabethOkerio** 2022-02-16 09:25 UTC
Labels: follow-up
