### ISSUE TITLE
Support TLS versioning in ODataClient

### ISSUE THREAD

**Issue by KanishManuja-MS** [OData/odata.net#1565] opened 2019-10-08 19:48 UTC
We updated our sample services to enforce TLS 1.2. However, ODataClient does not support TLS versioning. 

### Assemblies affected
ODL  7.6.1 and previous versions.

### Reproduce steps

Try calling one of the reference services with OData client. 

### Expected result

The request should succeed. Moreover, ODataClient should provide a configuration to specify the TLS version. 

### Actual result
```
Unhandled Exception:   System.InvalidOperationException: An error occurred while processing this   request. ---> Microsoft.OData.Client.DataServiceTransportException: The   underlying connection was closed: An unexpected error occurred on a send.   ---> System.Net.WebException: The underlying connection was closed: An   unexpected error occurred on a send. ---> System.IO.IOException: Unable to   read data from the transport connection: An existing connection was forcibly   closed by the remote host. ---> System.Net.Sockets.SocketException: An   existing connection was forcibly closed by the remote host
at   System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
at   System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
--- End of inner exception stack trace ---
at System.Net.TlsStream.EndWrite(IAsyncResult   asyncResult)
at System.Net.PooledStream.EndWrite(IAsyncResult   asyncResult)
at   System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
--- End of inner exception stack trace ---
at   System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
at   Microsoft.OData.Client.HttpWebRequestMessage.EndGetResponse(IAsyncResult   asyncResult)
Unhandled Exception:   System.InvalidOperationException: An error occurred while processing this   request. ---> Microsoft.OData.Client.DataServiceTransportException: The   underlying connection was closed: An unexpected error occurred on a send.   ---> System.Net.WebException: The underlying connection was closed: An   unexpected error occurred on a send. ---> System.IO.IOException: Unable to   read data from the transport connection: An existing connection was forcibly   closed by the remote host. ---> System.Net.Sockets.SocketException: An   existing connection was forcibly closed by the remote host
at   System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
at   System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
--- End of inner exception stack trace ---
at System.Net.TlsStream.EndWrite(IAsyncResult   asyncResult)
at System.Net.PooledStream.EndWrite(IAsyncResult   asyncResult)
at   System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
--- End of inner exception stack trace ---
at   System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
at   **Microsoft.OData.Client.HttpWebRequestMessage.EndGetResponse(IAsyncResult   asyncResult)**
```

**Comment by habbes** [comment] 2020-01-06 15:38
Hi @KanishManuja-MS could you specify the reference services we could use to reproduce the issue? I created an OData client for the TripPin service and was able to fetch data from the service successfully. My code was using OData client 7.6.2. I tried to use 7.6.1 and I was still able to fetch data from the service. Or could you share more detailed steps on how to reproduce the issue?

**Comment by KanishManuja-MS** [comment] 2020-01-06 18:05
@habbes I wonder if that is because we have turned off the minimum TLS version for the sample service. You would need to JIT into azure portal and check that. I will confirm if that is the case once I have my saw running.

**Comment by habbes** [comment] 2020-01-07 09:49
Hi @KanishManuja-MS. I'm not sure what you meant by "JIT into azure portal", but I have tried other ways to reproduce the issue without much success.

I have a created a sample OData service and an OData client application. I enforced TLS 1.2 on the service and was still able to successfully fetch data using the OData client. Here's the repository containing both the service and client projects: https://github.com/habbes/ODataTlsVersionBug

Furthermore, I used an online tool to check the TLS versions used by the TripPin service, and the tool reported that TripPin is configured with TLS 1.2, but not TLS 1.1 or lower: https://www.ssllabs.com/ssltest/analyze.html?d=services.odata.org&hideResults=on

So this could indicated a ossibility that the issue is not with the OData client. Could you share more details about your environment? Like the version of .Net Framework or .Net core that you were using and OS? Could you also check the `ServicePointManager.SecurityProtocol` used by your client code?

In recent versions of .Net,  `ServicePointManager.SecurityProtocol` defaults to the system default, which is determined by the OS or other system configuration. So it's also possible that the system itself did not support TLS 1.2.

**Comment by habbes** [comment] 2020-01-08 04:49
As discussed with @KanishManuja-MS, I am closing this issue. The issue can be re-opened if the error re-surfaces.

**Closed by habbes** 2020-01-08 04:49 UTC
Labels: P2, bug, client, good first issue
