### ISSUE TITLE
Linq is a leaky abstraction, needs some documentation or a change with some http 404 errors

### ISSUE THREAD

**Issue by nicenemo** [OData/odata.net#533] opened 2016-04-11 15:26 UTC
Searching for a non existing element using  a primary key and and search for an element using a primary key and andother property using LINQ produce different urls but also different results.

### Assemblies affected
 OData .Net lib 6.15-beta
Note: We are using OLingo on the serverside.

### Reproduce steps
Observer the following two tests that only differe in the where clause.

- The first test is equivalent to a `ctx.Documents.Bykey(sessionId)` call
- The first produces a http 404  error.
- The second produces an url with a a $filter clause.
- The second results in an Empty set.

```
    /// <summary>
    /// Find non existing session.
    /// </summary>
    [Fact()]
    public void FindNonExistingSessionWithOnlySessionIdinWhereClauseThrowsException()
    {
      var ctx = CreateContext();
      var fakedSessionId = PostFakeSessions(ctx, 1).Single();
      try
      {

        Action action = () =>
        {
          var nonExistingSessionId = Guid.NewGuid().ToString();
          var session = (from ses in ctx.Sessions
                         where ses.SessionId == nonExistingSessionId
                         select ses).ToArray().FirstOrDefault();
        };

        Assert.Throws<DataServiceQueryException>(action);

      }
      finally
      {
        DeleteDocuments(ctx, fakedSessionId);
      }
    }

    /// <summary>
    /// Find non existing session.
    /// </summary>
    [Fact()]
    public void FindNonExistingSession()
    {
      var ctx = CreateContext();
      var fakedSessionId = PostFakeSessions(ctx, 1).Single();
      try
      {

        Action action = () =>
        {
          var nonExistingSessionId = Guid.NewGuid().ToString();
          var session = (from ses in ctx.Sessions
                         where ses.SessionId == nonExistingSessionId && ses.CreationDate.Value.Hour>0
                         select ses).ToArray().FirstOrDefault();
          Assert.Null(session);
        };

        action();

      }
      finally
      {
        DeleteDocuments(ctx, fakedSessionId);
      }
    }

```
### Expected result
Warn programmers for this in the documentation or catch 404 silently and produce an empty set clientside.

**Comment by markdstafford** [comment] 2016-04-26 04:13
They always say it's best to preface any bad news with a compliment, right? Thank you for submitting all of the issues recently (and in the past as well). It's good to have vocal people in our community.

In this particular case, I'm going to close this issue as "by design". If you want to discuss further, it's perfectly fine to reopen the issue, but let me try to explain a bit more than just saying "by design".

LINQ providers are interesting beasts, and as you've pointed out they don't map up 100% to OData query semantics. Overall we think it's helpful to .NET developers as they don't need to learn OData query syntax if they know LINQ. But that means we have to make calls about how to translate certain LINQ queries. Years ago we decided that if the only thing the where clause contains is an equality match on the key property, we should translate that to normal key syntax. Anything more complicated should just get stuffed into the $filter expression. IOW we consciously made the decision not to extricate any key properties since things get complicated quickly (e.g., ||, etc) and the value is low. The point here is that the different URLs you're seeing generated are by design.

We could always improve at documentation, but at this point we are focused on an upcoming breaking changes release (things tracked against the 7.0 milestone) and we have a hard date to get that out, so addressing this in documentation is low on our priority list right now. We would happily accept pull requests to our documentation (https://github.com/OData/odata.github.io) as well, though, so if you have time to write something up we'd love to reopen this issue and get it fixed properly.

I know that's not the answer you want to hear, but hopefully at least getting the explanation helps.

**Closed by markdstafford** 2016-04-26 04:13 UTC
