### ISSUE TITLE
Make dependency injection easier in ODL

### ISSUE THREAD

**Issue by habbes** [OData/odata.net#2484] opened 2022-08-17 15:44 UTC
The current dependency injection support in Microsoft.OData.Core requires a lot of effort for the developer to override default services.

Let's take the message writer for example. To inject services to `ODataMessageWriter`, you need to make your custom implementation of `IODataRequest/ResponseMessage` also extend `IContainerProvider` then implement an `IServiceProvider Container { get; }` property.

This takes a bit of work, *but it's not that bad*. One could easily create a `ServiceCollection` instance, add services there, and call `serviceCollection.BuildServiceProvider` to create the container.

**However**:

If you inject a few customs services to the container and pass that to `ODataMessageWriter`, you will likely run into a number of exceptions. This is because `ODataMessageWriter` requires a number of services. If you provide a service container, but don't inject those required services, it will throw an exception instead of falling back to some internal defaults.

You can fix this issue by calling the `AddDefaultODataServices()` extension method to inject all the required services into your container with default built-in implementations before injecting custom services.

But here's the problem: this extension expects an `IODataContainerBuilder` interface. This is an OData-specific interface for building service containers. Its stated goal is to decouple ODL from any specific DI implementation or library (including `Microsoft.Extensions.DependencyInjection`). While this is a reasonable design choice, there's no default implementation provided. This application that consumes ODL has to implement its own custom `IODataContainerBuilder` class in order to override custom services. A common approach is to implement a thin wrapper over `ServiceCollection` from `Microsoft.Extensions.DependencyInjection` (See [this sample implementation](https://github.com/OData/AspNetCoreOData/blob/main/src/Microsoft.AspNetCore.OData/Abstracts/DefaultContainerBuilder.cs) in Web API 8).

I propose that we simply dependency injection in ODL 8. Here are some of the things we can consider:

- Expose a default implementation of `IODataContainerBuilder` (e.g. `DefaultODataContainerBuilder`).
- Consider whether `IODataResponseMessage` is the ideal place to stash the service container. In my opinion, this is very unintuitive. Maybe a property or constructor in `ODataMessageWriterSettings` or even `ODataMessageWriter` would be more natural candidates?
- Do we really need a custom `IODataContainerBuilder` interface?

### Assemblies affected

Microsoft.OData.Core 7.x

### Reproduce steps

*The simplest set of steps to reproduce the issue. If possible, reference a commit that demonstrates the issue.*

### Expected result

*What would happen if there wasn't a bug.*

### Actual result

*What is actually happening.*

### Additional detail

*Optional, details of the root cause if known. Delete this section if you have no additional details to add.*

**Comment by corranrogue9** [comment] 2022-08-17 16:18
Adding some comments to the other issue, but considering this a duplicate of https://github.com/OData/odata.net/issues/2385 otherwise.

**Closed by corranrogue9** 2022-08-17 16:18 UTC
Labels: Major release opportunity

**Comment by robertmclaws** [comment] 2022-08-17 17:30
So, at one point, I had a pretty massive PR that refactored the DI to make it much more flexible, to integrate it with the main DI container where necessary, and had some great code for failing over from the OData-specific container to the root container. We had to shelve that to get OData 8.0 out the door, but I think it's going to be a good time to re-address that work and see if we can get it integrated.
