### ISSUE TITLE
Key Aliases are not supported

### ISSUE THREAD

**Issue by corranrogue9** [OData/odata.net#2770] opened 2023-10-16 18:05 UTC
Using the `Alias` attribute in the `PropertyRef` defined for a `Key` is not considered a valid model.

### Assemblies affected

At least 7.14.0

### Reproduce steps

A test that repros the issue can be found [here](https://github.com/OData/odata.net/commit/85a4ab05e23c89cfa78ef9a4cdd5957fa14311ae).

### Expected result

The test should pass.

### Actual result

The rest fails. 

### Additional detail

Example 11 of the [standard](https://docs.oasis-open.org/odata/odata-csdl-xml/v4.01/odata-csdl-xml-v4.01.html#sec_Key) shows the use of an alias for a key.

**Comment by gathogojr** [comment] 2023-10-17 11:08
@corranrogue9 There's an open pull request https://github.com/OData/odata.net/pull/2411 by @ElizabethOkerio to support this.
Possible duplicate of https://github.com/OData/odata.net/issues/1817?
@xuzhg Did [this commit](https://github.com/OData/odata.net/commit/5a303fa433c0349276104402260da875cef814f8) fix #1817?

**Comment by gathogojr** [comment] 2023-10-17 16:11
Duplicate of #1817

**Closed by gathogojr** 2023-10-17 16:11 UTC
